### ISSUE TITLE
qemu to install   DVRF_v03

### ISSUE THREAD

**Issue by muguang** [praetorian-inc/DVRF#1]
hello , i am a beginner   and i  take problem now.
 wheater can i install the DVRF_v03 by QEMU  ??
                 for  when i  `binwalk -eM DVRF_v03.bin`   and there is only a piggy file in the folder, ( i referto the link you given ：https://www.praetorian.com/blog/getting-started-with-damn-vulnerable-router-firmware-dvrf-v0.1）   and there is somewhere different 

Thankyou

**Comment by b1ack0wl** [comment]
Hey! Thanks for taking an interest in the project. So it looks like you're missing dependencies in order to extract the squash-fs. If you look at the Binwalk project you should see a 'deps.sh' file, this file when ran will download the libraries needed to use binwalk properly. If you have any more issues please feel free to ask!

**Comment by muguang** [comment]
Thank you for your response!
 I install it by apt-get  and then also download the source code and  compile it , but i also face the problem  just like this  
<img width="1199" alt="2016-07-31 12 20 35" src="https://cloud.githubusercontent.com/assets/7148519/17271721/02c72058-56b6-11e6-8b1a-c1e75f8efb48.png">

it seems that binwalk can extract the squash-fs for the below one ?  
but can't extract the squash-fs on the DVRF_v03.bin  
i don't known where wrong.
Thank you very much!

**Comment by b1ack0wl** [comment]
The version of Binwalk that is on apt-get is old. Please uninstall Binwalk and download the newest version and compile it from here: https://github.com/devttys0/binwalk

Remember to execute the `deps.sh` shell script first since it will download and install the libraries needed to run Binwalk.

**Comment by muguang** [comment]
Thanks very much!
I know what wrong, that the first firemware i downloaded is incompleted.
Now it works well .
Thank you.
