### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by igogo-x86** [praetorian-inc/DVRF#2]
Hello! For my tasks i want to make this firmware for different platforms. First of all i have got a trouble compiling it using toolchain attached to the project. Here is log file:

[DVRF_makefile_output.txt](https://github.com/praetorian-inc/DVRF/files/615845/DVRF_makefile_output.txt)

I've tried using latest Debian OS and Fedora 11 and the problem is the same

**Comment by b1ack0wl** [comment]
I was able to reproduce the issue and I'm currently working on providing a solution.  I'll update this ticket once I pinpoint the issue.

**Comment by b1ack0wl** [comment]
So, there were several problems. Some of the header files within the linux2.6, iptables, ipupdate, popt, and the include files under release/src were corrupted. I've corrected all of these files and I'm running through some tests to make sure that this issue is resolved.

**Comment by b1ack0wl** [comment]
Also, the uclibc buildroot was missing which I've added. I'll update this ticket with a location of the new fork and will submit a pull request to this repro.

**Comment by b1ack0wl** [comment]
I've forked and updated the repro. Please give this a try - https://github.com/b1ack0wl/DVRF
